services:
  db:
    image: postgres:16-alpine
    container_name: socialnetwork-pg
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    volumes:
      - social-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  social-db-data:
